spring:
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: info

mongo:
  uri: mongodb+srv://bookStoreAdmin:LVxAm0PQJWdT@cluster0-j6mpg.mongodb.net/test?retryWrites=true&w=majority
  basename: BookStore

token:
  secret: SIxkA7wGqbgmDtoM9bMcTTJ50SIuVfODlQApYbGSr8IM49JsqhZQwWEenKDq7g6dGfRedSjklUY
  expirationTime: 28800