spring:
  data:
    mongodb:
      database: book_store
#      uri: mongodb://localhost:27017/book_store

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: debug

mongo:
  uri: mongodb://localhost:27017/
  basename: book_store

token:
  secret: SIxkA7wGqbgmDtoM9bMcTTJ50SIuVfODlQApYbGSr8IM49JsqhZQwWEenKDq7g6dGfRedSjklUY
  expirationTime: 28800